name: Update M3U8

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reponu klonla
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Default olaraq true-dur, onu sÃ¶ndÃ¼rÃ¼rÃ¼k ki, Ã¶z token ilÉ™ push edÉ™k.

      - name: Python quraÅŸdÄ±r
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: M3U8 faylÄ±nÄ± yarat
        run: python generate_m3u8.py

      - name: Git konfiqurasiya
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: Push dÉ™yiÅŸikliklÉ™ri
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add trt_haber_live.m3u8
          git diff --cached --quiet || (git commit -m "ğŸ” Æl ilÉ™ yenilÉ™mÉ™" && git push origin HEAD:${{ github.ref_name }})
