name: Update M3U8

on:
  schedule:
    - cron: '0 */6 * * *'  # HÉ™r 6 saatda bir iÅŸlÉ™
  workflow_dispatch:       # Manual iÅŸlÉ™tmÉ™k Ã¼Ã§Ã¼n

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reponu klonla
        uses: actions/checkout@v3

      - name: Python quraÅŸdÄ±r
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: M3U8 faylÄ±nÄ± yarat
        run: python generate_m3u8.py

      - name: YaranmÄ±ÅŸ faylÄ± commit et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trt_haber_live.m3u8
          git commit -m "ğŸ” Avtomatik yenilÉ™mÉ™"
          git push
