name: Update M3U8

on:
  workflow_dispatch:  # Bu hissÉ™ sayÉ™sindÉ™ É™l ilÉ™ iÅŸÉ™ salmaq mÃ¼mkÃ¼n olur

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Reponu klonla
        uses: actions/checkout@v3

      - name: Python quraÅŸdÄ±r
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: M3U8 faylÄ±nÄ± yarat
        run: python generate_m3u8.py

      - name: YaranmÄ±ÅŸ faylÄ± commit et
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add trt_haber_live.m3u8
          git commit -m "ğŸ” Æl ilÉ™ yenilÉ™mÉ™" || echo "No changes to commit"
          git push
