name: Update Live Stream M3U8

on:
  schedule:
    - cron: '*/15 * * * *'  # hÉ™r 15 dÉ™qiqÉ™
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip3 install -U yt-dlp

      - name: Run update script
        run: |
          chmod +x update_stream.sh
          ./update_stream.sh

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions.github.com"
          git add stream.m3u8 || true
          git commit -m "ðŸ”„ Update stream.m3u8" || echo "No changes"
          git push
