name: Update M3U8

on:
  schedule:
    - cron: '*/15 * * * *'  # hÉ™r 15 dÉ™qiqÉ™ iÅŸÉ™ dÃ¼ÅŸÉ™cÉ™k
  workflow_dispatch:        # É™l ilÉ™ dÉ™ iÅŸÉ™ salmaq olur

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repo klonlanÄ±r
        uses: actions/checkout@v3

      - name: yt-dlp quraÅŸdÄ±rÄ±lÄ±r
        run: |
          sudo apt update
          sudo apt install -y ffmpeg python3-pip
          pip3 install yt-dlp

      - name: Skript iÅŸlÉ™dilir
        run: |
          chmod +x update_stream.sh
          ./update_stream.sh

      - name: Git dÉ™yiÅŸikliklÉ™rini push et
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add stream.m3u8 || true
          git commit -m "ğŸ” m3u8 yenilÉ™ndi" || echo "DÉ™yiÅŸiklik yoxdur"
          git push
